services:
  llm-ollama-deepseek:
    build: ./ollama
    container_name: llm-ollama-deepseek
    pull_policy: always
    tty: true
    restart: unless-stopped
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  llm-based-app-fastapi:
    build: ./app
    container_name: llm-based-fastapi
    ports:
      - "7777:8000"
      - "5678:5678"
    restart: unless-stopped
    depends_on:
      - llm-ollama-deepseek
    networks:
      - app-network
    environment:
      - username=username123
      - password=password123
      - DEBUG_MODE=true
networks:
  app-network:
    driver: bridge
